# Generated by Django 4.2.25 on 2025-10-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_student',
        ),
    ]
